package com.credibledoc.combiner.node.log;

import java.util.ArrayList;
import java.util.List;

/**
 * A stateful service. Contains a list of {@link NodeLog}s.
 *
 * @author Kyrylo Semenko
 */
public class NodeLogRepository {

    /**
     * Singleton.
     */
    private static NodeLogRepository instance;

    /**
     * @return The {@link NodeLogRepository} singleton.
     */
    public static NodeLogRepository getInstance() {
        if (instance == null) {
            instance = new NodeLogRepository();
        }
        return instance;
    }

    /**
     * Files generated by some application.
     */
    private List<NodeLog> nodeLogs = new ArrayList<>();

    /**
     * @return the {@link #nodeLogs} value
     */
    List<NodeLog> getNodeLogs() {
        return nodeLogs;
    }

}
