// Generated by delombok at Wed May 01 19:36:18 CEST 2019
package com.credibledoc.combiner.doc;

import com.credibledoc.substitution.core.configuration.Configuration;
import com.credibledoc.substitution.core.configuration.ConfigurationService;
import com.credibledoc.substitution.reporting.markdown.MarkdownService;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

/**
 * The main class for generation of documentation for the log-combiner library and tool.
 *
 * @author Kyrylo Semenko
 */
public class LogCombinerDocMain {
    @java.lang.SuppressWarnings("all")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(LogCombinerDocMain.class);

    /**
     * The main method for generation of documentation of the credibledoc-substitution tool.
     */
    public static void main(String[] args) {
        try {
            log.info("Application \'{}\' launched.", LogCombinerDocMain.class.getSimpleName());
            try (AnnotationConfigApplicationContext applicationContext = new AnnotationConfigApplicationContext(LogCombinerDocMain.class)) {
                applicationContext.start();
                log.info("Spring ApplicationContext created and started");
                Configuration configuration = ConfigurationService.getInstance().getConfiguration();
                configuration.setTemplatesResource("template/markdown/doc");
                MarkdownService.getInstance().generateContentFromTemplates();
            }
        } catch (Exception e) {
            log.error(e.getMessage(), e);
        }
        log.info("Application finished");
    }
}
