package org.credibledoc.substitution.doc.node.log;

import org.springframework.stereotype.Repository;

import java.util.ArrayList;
import java.util.List;

/**
 * A stateful service. Contains a list of {@link NodeLog}s.
 *
 * @author Kyrylo Semenko
 */
@Repository
public class NodeLogRepository {

    /**
     * Files generated by {@link org.credibledoc.substitution.doc.module.tactic.TacticHolder}
     */
    private List<NodeLog> nodeLogs = new ArrayList<>();

    /**
     * @return the {@link #nodeLogs} value
     */
    public List<NodeLog> getNodeLogs() {
        return nodeLogs;
    }

    /**
     * @param nodeLogs see the {@link #nodeLogs} field
     */
    public void setNodeLogs(List<NodeLog> nodeLogs) {
        this.nodeLogs = nodeLogs;
    }
}
