package com.credibledoc.combiner.node.log;

import com.credibledoc.combiner.application.Application;

import java.util.ArrayList;
import java.util.List;

/**
 * A stateful service. Contains a list of {@link NodeLog}s.
 *
 * @author Kyrylo Semenko
 */
public class NodeLogRepository {
    // TODO Kyrylo Semenko - nesmi byt singleton aby slo pustit ve vice instancich

    /**
     * Singleton.
     */
    private static NodeLogRepository instance;

    /**
     * @return The {@link NodeLogRepository} singleton.
     */
    public static NodeLogRepository getInstance() {
        if (instance == null) {
            instance = new NodeLogRepository();
        }
        return instance;
    }

    /**
     * Files generated by {@link Application}
     */
    private List<NodeLog> nodeLogs = new ArrayList<>();

    /**
     * @return the {@link #nodeLogs} value
     */
    public List<NodeLog> getNodeLogs() {
        return nodeLogs;
    }

    /**
     * @param nodeLogs see the {@link #nodeLogs} field
     */
    public void setNodeLogs(List<NodeLog> nodeLogs) {
        this.nodeLogs = nodeLogs;
    }
}
