package com.credibledoc.combiner.state;

import com.credibledoc.combiner.node.file.NodeFile;

import java.util.Set;
import java.util.TreeSet;

/**
 * Stateful object. Contains state of loaded {@link #nodeFiles}, for example the {@link #currentNodeFile}.
 *
 * @author Kyrylo Semenko
 */
public class FilesMergerState {

    /**
     * Last used {@link NodeFile} from {@link #nodeFiles}.
     */
    private NodeFile currentNodeFile;

    /**
     * Log files generated by some application.
     */
    private Set<NodeFile> nodeFiles = new TreeSet<>();

    /**
     * @return The {@link #nodeFiles} field value.
     */
    public Set<NodeFile> getNodeFiles() {
        return nodeFiles;
    }

    /**
     * @param nodeFiles see the {@link #nodeFiles} field description.
     */
    public void setNodeFiles(Set<NodeFile> nodeFiles) {
        this.nodeFiles = nodeFiles;
    }

    /**
     * @return The {@link #currentNodeFile} field value.
     */
    public NodeFile getCurrentNodeFile() {
        return currentNodeFile;
    }

    /**
     * @param currentNodeFile see the {@link #currentNodeFile} field description.
     */
    public void setCurrentNodeFile(NodeFile currentNodeFile) {
        this.currentNodeFile = currentNodeFile;
    }
}
